export type PriceType = "hour" | "package" | "day" | "night"

export const siteContent = {
  brand: {
    name: "F16 Arena",
    shortName: "F16",
    subtitle: "Cyber Lounge & Extra",
    city: "Усть-Каменогорск",
    address: "ул. 30-й Гвардейской Дивизии, 24/1",
    email: "info@f16arena.kz",
    workingLabel: "24/7 без выходных",
  },
  seo: {
    title: "F16 Arena — Компьютерный клуб, PS5 и SimRacing в Усть-Каменогорске",
    description:
      "Топовое железо, PS5, SimRacing и бронирование через WhatsApp 24/7. Актуальные тарифы и контакты F16 Arena в Усть-Каменогорске.",
    ogImage: "/dark-gaming-room-with-neon-lights-and-pc-setups.png",
    ogImageAlt: "Игровая зона F16 Arena с неоновым освещением и компьютерными сетапами",
  },
  contacts: {
    phones: [
      {
        id: "pc",
        label: "PC CLUB",
        shortLabel: "PC",
        phone: "+7 (708) 016-17-20",
        phoneRaw: "77080161720",
        accentClass: "text-blue-500",
        badgeClass: "bg-blue-500/10",
      },
      {
        id: "ps5",
        label: "PS5",
        shortLabel: "PS5",
        phone: "+7 (708) 016-00-07",
        phoneRaw: "77080160007",
        accentClass: "text-primary",
        badgeClass: "bg-primary/10",
      },
    ],
    socials: [
      { name: "Instagram", href: "https://instagram.com/f16arena_", colorClass: "text-pink-500" },
      { name: "Telegram", href: "https://t.me/f16arena", colorClass: "text-blue-400" },
      { name: "WhatsApp", href: "https://wa.me/77080161720", colorClass: "text-green-500" },
    ],
    workingHours: [{ day: "Ежедневно", hours: "24/7" }],
  },
  hero: {
    badge: "Работаем 24/7, бронь подтверждаем через WhatsApp",
    description: "Топовое железо, PS5 и SimRacing. Пространство для игр, отдыха и встреч в Усть-Каменогорске.",
    typedWords: ["Компьютеры", "PS5", "SimRacing", "вечеринки", "турниры"],
    stats: [
      { label: "ПК всего", value: 67, description: "игровых станций", icon: "monitor" },
      { label: "PS5", value: 4, description: "консоли", icon: "gamepad" },
      { label: "SimRacing", value: 2, description: "установки", icon: "car" },
      { label: "Мониторы", value: 600, description: "Hz макс", icon: "zap", suffix: "Hz" },
    ],
    quickFacts: ["24/7 без выходных", "До 70 гостей", "600Hz мониторы"],
    salesPoints: [
      {
        title: "Бронь за 30 секунд",
        description: "Оставь заявку и сразу перейди в WhatsApp для подтверждения.",
      },
      {
        title: "Два контакта без путаницы",
        description: "Отдельные номера для ПК и PS5, чтобы тебя быстро соединили с нужной зоной.",
      },
      {
        title: "Приезжай в любое время",
        description: "Мы действительно открыты 24/7, без выходных и ночных пауз.",
      },
    ],
  },
  pricing: {
    sortOptions: [
      { id: "default", label: "По умолчанию" },
      { id: "price-asc", label: "Цена ↑" },
      { id: "price-desc", label: "Цена ↓" },
      { id: "popular", label: "Популярные" },
    ],
    timeFilters: [
      { id: "all", label: "Все" },
      { id: "hour", label: "Час" },
      { id: "package", label: "Пакеты" },
      { id: "day", label: "День" },
      { id: "night", label: "Ночь" },
    ],
    zones: [
      {
        name: "Standart",
        pcs: "25 ПК",
        description: "Надёжные ПК для стабильной игры",
        icon: "monitor",
        color: "text-muted-foreground",
        bgColor: "bg-secondary/50",
        prices: [
          { label: "Час", value: 900, unit: "₸/час", type: "hour" },
          { label: "2+1", value: 1800, unit: "₸ за 3ч", type: "package", discount: 10 },
          { label: "3+2", value: 2700, unit: "₸ за 5ч", type: "package", discount: 15 },
          { label: "День", value: 1500, unit: "₸/день", type: "day" },
          { label: "Ночь", value: 3000, unit: "₸/ночь", type: "night" },
        ],
      },
      {
        name: "Standart Premium",
        pcs: "30 ПК",
        description: "Улучшенные мониторы, высокая частота кадров",
        icon: "star",
        color: "text-blue-400",
        bgColor: "bg-blue-500/10",
        featured: false,
        prices: [
          { label: "Час", value: 1200, unit: "₸/час", type: "hour" },
          { label: "2+1", value: 2400, unit: "₸ за 3ч", type: "package", discount: 10 },
          { label: "3+2", value: 3600, unit: "₸ за 5ч", type: "package", discount: 15 },
          { label: "День", value: 2500, unit: "₸/день", type: "day" },
          { label: "Ночь", value: 4500, unit: "₸/ночь", type: "night" },
        ],
      },
      {
        name: "VIP",
        pcs: "6 ПК",
        description: "Премиум-станции для тех, кто хочет максимум",
        icon: "crown",
        color: "text-primary",
        bgColor: "bg-primary/10",
        featured: true,
        prices: [
          { label: "Час", value: 1400, unit: "₸/час", type: "hour" },
          { label: "2+1", value: 2800, unit: "₸ за 3ч", type: "package", discount: 10 },
          { label: "3+2", value: 4200, unit: "₸ за 5ч", type: "package", discount: 15 },
          { label: "Ночь", value: 5000, unit: "₸/ночь", type: "night" },
        ],
      },
      {
        name: "PRO",
        pcs: "5 ПК",
        description: "Топовое железо для киберспортсменов",
        icon: "zap",
        color: "text-orange-400",
        bgColor: "bg-orange-500/10",
        featured: false,
        prices: [
          { label: "Час", value: 1800, unit: "₸/час", type: "hour" },
          { label: "2+1", value: 3600, unit: "₸ за 3ч", type: "package", discount: 10 },
          { label: "3+2", value: 5400, unit: "₸ за 5ч", type: "package", discount: 15 },
          { label: "Ночь", value: 5800, unit: "₸/ночь", type: "night" },
        ],
      },
      {
        name: "Elite",
        pcs: "1 ПК",
        description: "Флагманская зона с топовой сборкой и монитором 600Hz",
        icon: "crown",
        color: "text-cyan-400",
        bgColor: "bg-cyan-500/10",
        featured: true,
        prices: [
          { label: "Час", value: 2800, unit: "₸/час", type: "hour" },
          { label: "2+1", value: 5600, unit: "₸ за 3ч", type: "package", discount: 10 },
          { label: "3+2", value: 8200, unit: "₸ за 5ч", type: "package", discount: 15 },
          { label: "Ночь", value: 10000, unit: "₸/ночь", type: "night" },
        ],
      },
    ],
  },
  extra: {
    filters: [
      { id: "all", label: "Все" },
      { id: "ps5", label: "PS5" },
      { id: "simracing", label: "SimRacing" },
    ],
    items: [
      {
        category: "PS5",
        icon: "gamepad",
        color: "text-blue-400",
        bgColor: "bg-blue-500/10",
        description: "Комфортные зоны с большими экранами, идеальны для компаний",
        popular: true,
        items: [
          { name: 'PS5 65"', price: 1200, priceStr: "1 200₸", note: "Почасовой тариф", billing: "hourly" },
          { name: 'PS5 75"', price: 1500, priceStr: "1 500₸", note: "Почасовой тариф", billing: "hourly" },
        ],
      },
      {
        category: "SimRacing",
        icon: "car",
        color: "text-orange-400",
        bgColor: "bg-orange-500/10",
        description: "Реалистичные кокпиты для полного погружения в гонку",
        popular: false,
        items: [
          { name: "Час", price: 2500, priceStr: "2 500₸", note: "Почасовой тариф", billing: "hourly" },
          { name: "2+1", price: 4800, priceStr: "4 800₸", note: "Фиксированный пакет на 3 часа", billing: "fixed" },
          { name: "3+2", price: 7200, priceStr: "7 200₸", note: "Фиксированный пакет на 5 часов", billing: "fixed" },
        ],
      },
    ],
    packages: [
      {
        name: "PS5 + PS5",
        price: "2 200₸",
        oldPrice: "2 400₸",
        duration: "1 час",
        subtitle: "Две консоли сразу",
        discount: true,
        popular: false,
      },
      {
        name: "PS5 + SimRacing",
        price: "3 300₸",
        oldPrice: "3 700₸",
        duration: "1 час",
        subtitle: "Для компании",
        discount: true,
        popular: true,
      },
      {
        name: "2 PS5 + SimRacing",
        price: "5 000₸",
        oldPrice: "6 200₸",
        duration: "1 час",
        subtitle: "Максимум развлечений",
        discount: true,
        popular: false,
      },
      {
        name: "Всё включено",
        price: "8 500₸",
        oldPrice: "10 000₸",
        duration: "2 часа",
        subtitle: "PS5 ×2 + SimRacing",
        discount: true,
        popular: false,
      },
    ],
  },
} as const
